api:
  postgRest:
    url: http://localhost:3000


server:
  port: 9000

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            redirect-uri: localhost:9000/login/oauth2/code/google
            scope:
              - email
              - profile
